project:
  output-dir: . 
  type: book
#  type: website

book:
  title: "My Notes"
  chapters:
    - index.qmd #required
    - geom.qmd
    - geom2.qmd
    - geom3.qmd
    - qj.qmd

#filters:
#  - showids2.lua

number-sections: true

execute:
  freeze: auto #do not remake unchanged .qmd files